CREATE TABLE "Earthquakes" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "location_id" bigint,
  "time_id" bigint,
  "magitude_id" bigint,
  "url" varchar,
  "status" varchar,
  "tsunami" int,
  "net" varchar,
  "code" varchar,
  "sources" varchar,
  "nst" bigint,
  "dmin" decimal,
  "rms" decimal,
  "gap" decimal,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "Types" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "earthquake_id" bigint,
  "type_eathquake" varchar,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "AssociatedEvent" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "earthquake_id" bigint,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "Location" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "longitude" decimal NOT NULL,
  "latitude" decimal NOT NULL,
  "dept" decimal NOT NULL,
  "place" varchar,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "Magnitudes" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "magnitude_value" decimal,
  "magnitude_type" varchar,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "Times" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "date_time" timestamp,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "Requests" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "request_url" varchar,
  "request_method" varchar,
  "request_headers" JSON,
  "request_body" JSON,
  "response_status_code" int,
  "response_body" JSON,
  "request_timestamp" timestamp DEFAULT (now()),
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "Users" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar,
  "password" varchar,
  "created_at" timestamp DEFAULT (now()),
  "role_id" bigint
);

CREATE TABLE "Roles" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_name" varchar
);

ALTER TABLE "Earthquakes" ADD FOREIGN KEY ("location_id") REFERENCES "Location" ("id");

ALTER TABLE "Earthquakes" ADD FOREIGN KEY ("time_id") REFERENCES "Times" ("id");

ALTER TABLE "Earthquakes" ADD FOREIGN KEY ("magitude_id") REFERENCES "Magnitudes" ("id");

ALTER TABLE "Types" ADD FOREIGN KEY ("earthquake_id") REFERENCES "Earthquakes" ("id");

ALTER TABLE "AssociatedEvent" ADD FOREIGN KEY ("earthquake_id") REFERENCES "Earthquakes" ("id");

ALTER TABLE "Users" ADD FOREIGN KEY ("role_id") REFERENCES "Roles" ("id");