// Code generated by ent, DO NOT EDIT.

package type_eathquake

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the type_eathquake type in the database.
	Label = "type_eathquake"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEarthquakeID holds the string denoting the earthquake_id field in the database.
	FieldEarthquakeID = "earthquake_id"
	// FieldTypeEathquake holds the string denoting the type_eathquake field in the database.
	FieldTypeEathquake = "type_eathquake"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeEarthquake holds the string denoting the earthquake edge name in mutations.
	EdgeEarthquake = "earthquake"
	// Table holds the table name of the type_eathquake in the database.
	Table = "Types"
	// EarthquakeTable is the table that holds the earthquake relation/edge.
	EarthquakeTable = "Types"
	// EarthquakeInverseTable is the table name for the Earthquake entity.
	// It exists in this package in order to avoid circular dependency with the "earthquake" package.
	EarthquakeInverseTable = "Earthquakes"
	// EarthquakeColumn is the table column denoting the earthquake relation/edge.
	EarthquakeColumn = "earthquake_id"
)

// Columns holds all SQL columns for type_eathquake fields.
var Columns = []string{
	FieldID,
	FieldEarthquakeID,
	FieldTypeEathquake,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Type_eathquake queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEarthquakeID orders the results by the earthquake_id field.
func ByEarthquakeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEarthquakeID, opts...).ToFunc()
}

// ByTypeEathquake orders the results by the type_eathquake field.
func ByTypeEathquake(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTypeEathquake, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByEarthquakeField orders the results by earthquake field.
func ByEarthquakeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEarthquakeStep(), sql.OrderByField(field, opts...))
	}
}
func newEarthquakeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EarthquakeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, EarthquakeTable, EarthquakeColumn),
	)
}
