// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/dialect/entsql"
)

type Earthquake struct {
	ent.Schema
}

func (Earthquake) Fields() []ent.Field {
	return []ent.Field{field.Int("id"), 
	field.Int("location_id").Optional(), 
	field.Int("time_id").Optional(), 
	field.Int("magitude_id").Optional(), 
	field.String("url").Optional(), 
	field.String("status").Optional(), 
	field.Int32("tsunami").Optional(), 
	field.String("net").Optional(), 
	field.String("code").Optional(), 
	field.String("sources").Optional(), 
	field.Int("nst").Optional(), 
	field.Float("dmin").Optional(), 
	field.Float("rms").Optional(), 
	field.Float("gap").Optional(), 
	field.Time("created_at").Optional(), 
	field.Time("updated_at").Optional()}
}
func (Earthquake) Edges() []ent.Edge {
	return []ent.Edge{edge.To("associated_events", AssociatedEvent.Type), edge.From("location", Location.Type).Ref("earthquakes").Unique().Field("location_id"), edge.From("magnitude", Magnitude.Type).Ref("earthquakes").Unique().Field("magitude_id"), edge.From("time", Time.Type).Ref("earthquakes").Unique().Field("time_id"), edge.To("types", Type_eathquake.Type)}
}
func (Earthquake) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "Earthquakes"}}
}