// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type Location struct {
	ent.Schema
}

func (Location) Fields() []ent.Field {
	return []ent.Field{field.Int("id"), field.Float("longitude"), field.Float("latitude"), field.Float("dept"), field.String("place").Optional(), field.Time("created_at").Optional(), field.Time("updated_at").Optional()}
}
func (Location) Edges() []ent.Edge {
	return []ent.Edge{edge.To("earthquakes", Earthquake.Type)}
}
func (Location) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "Location"}}
}
