// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type Request struct {
	ent.Schema
}

func (Request) Fields() []ent.Field {
	return []ent.Field{field.Int("id"), 
	field.String("request_url").Optional(), 
	field.String("request_method").Optional(), 
	field.JSON("request_headers", map[string]interface{}{}).Optional(), 
	field.JSON("request_body", map[string]interface{}{}).Optional(), 
	field.Int32("response_status_code").Optional(), 
	field.JSON("response_body", map[string]interface{}{}).Optional(), 
	field.Time("request_timestamp").Optional(), 
	field.Time("created_at").Optional(), 
	field.Time("updated_at").Optional()}

}
func (Request) Edges() []ent.Edge {
	return nil
}
func (Request) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "Requests"}}
}
