// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type Role struct {
	ent.Schema
}

func (Role) Fields() []ent.Field {
	return []ent.Field{field.Int("id"), field.String("role_name").Optional()}
}
func (Role) Edges() []ent.Edge {
	return []ent.Edge{edge.To("users", User.Type)}
}
func (Role) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "Roles"}}
}
