// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type Type_eathquake struct {
	ent.Schema
}

func (Type_eathquake) Fields() []ent.Field {
	return []ent.Field{field.Int("id"), 
	field.Int("earthquake_id").Optional(), 
	field.String("type_eathquake").Optional(), 
	field.Time("created_at").Optional(), 
	field.Time("updated_at").Optional()}
}
func (Type_eathquake) Edges() []ent.Edge {
	return []ent.Edge{edge.From("earthquake", Earthquake.Type).Ref("types").Unique().Field("earthquake_id")}
}
func (Type_eathquake) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "Types"}}
}
