// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AssociatedEvent struct {
	ID           int    `json:"id"`
	EarthquakeID []*int `json:"earthquake_id"`
	CreateAt     string `json:"create_at"`
	UpdateAt     string `json:"update_at"`
}

type DayInput struct {
	Day *int `json:"day,omitempty"`
}

type EarthquakeFilter struct {
	Magnitude      *float64 `json:"magnitude,omitempty"`
	Place          *string  `json:"place,omitempty"`
	TypeEarthquake *string  `json:"type_earthquake,omitempty"`
}

type Earthquakes struct {
	ID         int      `json:"id"`
	LocationID int      `json:"location_id"`
	TimeID     int      `json:"time_id"`
	MagitudeID int      `json:"magitude_id"`
	URL        *string  `json:"url,omitempty"`
	Status     *string  `json:"status,omitempty"`
	Tsunami    *string  `json:"tsunami,omitempty"`
	Net        *string  `json:"net,omitempty"`
	Code       *string  `json:"code,omitempty"`
	Sources    *string  `json:"sources,omitempty"`
	Nst        *int     `json:"nst,omitempty"`
	Dmin       *float64 `json:"dmin,omitempty"`
	Rms        *float64 `json:"rms,omitempty"`
	Gap        *float64 `json:"gap,omitempty"`
	CreateAt   string   `json:"create_at"`
	UpdateAt   string   `json:"update_at"`
}

type Location struct {
	ID        int     `json:"id"`
	Longitude float64 `json:"longitude"`
	Latitude  float64 `json:"latitude"`
	Dept      float64 `json:"dept"`
	Place     string  `json:"place"`
	CreateAt  string  `json:"create_at"`
	UpdateAt  string  `json:"update_at"`
}

type Magnitudes struct {
	ID            int      `json:"id"`
	MagitudeValue *float64 `json:"magitude_value,omitempty"`
	MagitudeType  *string  `json:"magitude_type,omitempty"`
	CreateAt      string   `json:"create_at"`
	UpdateAt      string   `json:"update_at"`
}

type PaginationInput struct {
	Limit  *int `json:"limit,omitempty"`
	Offset *int `json:"offset,omitempty"`
}

type Query struct {
}

type Requests struct {
	ID                 *int    `json:"id,omitempty"`
	RequestURL         *string `json:"request_url,omitempty"`
	RequestMethod      *string `json:"request_method,omitempty"`
	RequestHeaders     *string `json:"request_headers,omitempty"`
	RequestBody        *string `json:"request_body,omitempty"`
	ResponseStatusCode *int    `json:"response_status_code,omitempty"`
	ResponseBody       *string `json:"response_body,omitempty"`
	RequestTimestamp   *string `json:"request_timestamp,omitempty"`
	CreateAt           *string `json:"create_at,omitempty"`
	UpdateAt           *string `json:"update_at,omitempty"`
}

type Roles struct {
	ID       int    `json:"id"`
	RoleName string `json:"role_name"`
}

type Times struct {
	ID       int    `json:"id"`
	DateTime string `json:"date_time"`
	CreateAt string `json:"create_at"`
	UpdateAt string `json:"update_at"`
}

type TypeEathquake struct {
	ID             int       `json:"id"`
	EarthquakeID   []*int    `json:"earthquake_id"`
	TypeEarthquake []*string `json:"type_earthquake"`
	CreateAt       string    `json:"create_at"`
	UpdateAt       string    `json:"update_at"`
}

type Users struct {
	ID       int    `json:"id"`
	UserName string `json:"user_name"`
	Password string `json:"password"`
	CreateAt string `json:"create_at"`
	RoleID   int    `json:"role_id"`
}
