// Code generated by ent, DO NOT EDIT.

package enttime

import (
	"assignment3/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Time {
	return predicate.Time(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Time {
	return predicate.Time(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Time {
	return predicate.Time(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Time {
	return predicate.Time(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Time {
	return predicate.Time(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Time {
	return predicate.Time(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Time {
	return predicate.Time(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Time {
	return predicate.Time(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Time {
	return predicate.Time(sql.FieldLTE(FieldID, id))
}

// DateTime applies equality check predicate on the "date_time" field. It's identical to DateTimeEQ.
func DateTime(v time.Time) predicate.Time {
	return predicate.Time(sql.FieldEQ(FieldDateTime, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Time {
	return predicate.Time(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Time {
	return predicate.Time(sql.FieldEQ(FieldUpdatedAt, v))
}

// DateTimeEQ applies the EQ predicate on the "date_time" field.
func DateTimeEQ(v time.Time) predicate.Time {
	return predicate.Time(sql.FieldEQ(FieldDateTime, v))
}

// DateTimeNEQ applies the NEQ predicate on the "date_time" field.
func DateTimeNEQ(v time.Time) predicate.Time {
	return predicate.Time(sql.FieldNEQ(FieldDateTime, v))
}

// DateTimeIn applies the In predicate on the "date_time" field.
func DateTimeIn(vs ...time.Time) predicate.Time {
	return predicate.Time(sql.FieldIn(FieldDateTime, vs...))
}

// DateTimeNotIn applies the NotIn predicate on the "date_time" field.
func DateTimeNotIn(vs ...time.Time) predicate.Time {
	return predicate.Time(sql.FieldNotIn(FieldDateTime, vs...))
}

// DateTimeGT applies the GT predicate on the "date_time" field.
func DateTimeGT(v time.Time) predicate.Time {
	return predicate.Time(sql.FieldGT(FieldDateTime, v))
}

// DateTimeGTE applies the GTE predicate on the "date_time" field.
func DateTimeGTE(v time.Time) predicate.Time {
	return predicate.Time(sql.FieldGTE(FieldDateTime, v))
}

// DateTimeLT applies the LT predicate on the "date_time" field.
func DateTimeLT(v time.Time) predicate.Time {
	return predicate.Time(sql.FieldLT(FieldDateTime, v))
}

// DateTimeLTE applies the LTE predicate on the "date_time" field.
func DateTimeLTE(v time.Time) predicate.Time {
	return predicate.Time(sql.FieldLTE(FieldDateTime, v))
}

// DateTimeIsNil applies the IsNil predicate on the "date_time" field.
func DateTimeIsNil() predicate.Time {
	return predicate.Time(sql.FieldIsNull(FieldDateTime))
}

// DateTimeNotNil applies the NotNil predicate on the "date_time" field.
func DateTimeNotNil() predicate.Time {
	return predicate.Time(sql.FieldNotNull(FieldDateTime))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Time {
	return predicate.Time(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Time {
	return predicate.Time(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Time {
	return predicate.Time(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Time {
	return predicate.Time(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Time {
	return predicate.Time(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Time {
	return predicate.Time(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Time {
	return predicate.Time(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Time {
	return predicate.Time(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.Time {
	return predicate.Time(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.Time {
	return predicate.Time(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Time {
	return predicate.Time(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Time {
	return predicate.Time(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Time {
	return predicate.Time(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Time {
	return predicate.Time(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Time {
	return predicate.Time(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Time {
	return predicate.Time(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Time {
	return predicate.Time(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Time {
	return predicate.Time(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.Time {
	return predicate.Time(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.Time {
	return predicate.Time(sql.FieldNotNull(FieldUpdatedAt))
}

// HasEarthquakes applies the HasEdge predicate on the "earthquakes" edge.
func HasEarthquakes() predicate.Time {
	return predicate.Time(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EarthquakesTable, EarthquakesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEarthquakesWith applies the HasEdge predicate on the "earthquakes" edge with a given conditions (other predicates).
func HasEarthquakesWith(preds ...predicate.Earthquake) predicate.Time {
	return predicate.Time(func(s *sql.Selector) {
		step := newEarthquakesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Time) predicate.Time {
	return predicate.Time(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Time) predicate.Time {
	return predicate.Time(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Time) predicate.Time {
	return predicate.Time(sql.NotPredicates(p))
}
