// Code generated by ent, DO NOT EDIT.

package ent

import (
	"assignment3/ent/associatedevent"
	"assignment3/ent/earthquake"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// AssociatedEvent is the model entity for the AssociatedEvent schema.
type AssociatedEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// EarthquakeID holds the value of the "earthquake_id" field.
	EarthquakeID int `json:"earthquake_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AssociatedEventQuery when eager-loading is set.
	Edges        AssociatedEventEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AssociatedEventEdges holds the relations/edges for other nodes in the graph.
type AssociatedEventEdges struct {
	// Earthquake holds the value of the earthquake edge.
	Earthquake *Earthquake `json:"earthquake,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// EarthquakeOrErr returns the Earthquake value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AssociatedEventEdges) EarthquakeOrErr() (*Earthquake, error) {
	if e.Earthquake != nil {
		return e.Earthquake, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: earthquake.Label}
	}
	return nil, &NotLoadedError{edge: "earthquake"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AssociatedEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case associatedevent.FieldID, associatedevent.FieldEarthquakeID:
			values[i] = new(sql.NullInt64)
		case associatedevent.FieldCreatedAt, associatedevent.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AssociatedEvent fields.
func (ae *AssociatedEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case associatedevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ae.ID = int(value.Int64)
		case associatedevent.FieldEarthquakeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field earthquake_id", values[i])
			} else if value.Valid {
				ae.EarthquakeID = int(value.Int64)
			}
		case associatedevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ae.CreatedAt = value.Time
			}
		case associatedevent.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ae.UpdatedAt = value.Time
			}
		default:
			ae.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AssociatedEvent.
// This includes values selected through modifiers, order, etc.
func (ae *AssociatedEvent) Value(name string) (ent.Value, error) {
	return ae.selectValues.Get(name)
}

// QueryEarthquake queries the "earthquake" edge of the AssociatedEvent entity.
func (ae *AssociatedEvent) QueryEarthquake() *EarthquakeQuery {
	return NewAssociatedEventClient(ae.config).QueryEarthquake(ae)
}

// Update returns a builder for updating this AssociatedEvent.
// Note that you need to call AssociatedEvent.Unwrap() before calling this method if this AssociatedEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (ae *AssociatedEvent) Update() *AssociatedEventUpdateOne {
	return NewAssociatedEventClient(ae.config).UpdateOne(ae)
}

// Unwrap unwraps the AssociatedEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ae *AssociatedEvent) Unwrap() *AssociatedEvent {
	_tx, ok := ae.config.driver.(*txDriver)
	if !ok {
		panic("ent: AssociatedEvent is not a transactional entity")
	}
	ae.config.driver = _tx.drv
	return ae
}

// String implements the fmt.Stringer.
func (ae *AssociatedEvent) String() string {
	var builder strings.Builder
	builder.WriteString("AssociatedEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ae.ID))
	builder.WriteString("earthquake_id=")
	builder.WriteString(fmt.Sprintf("%v", ae.EarthquakeID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(ae.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(ae.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AssociatedEvents is a parsable slice of AssociatedEvent.
type AssociatedEvents []*AssociatedEvent
