// Code generated by ent, DO NOT EDIT.

package ent

import (
	"assignment3/ent/associatedevent"
	"assignment3/ent/earthquake"
	"assignment3/ent/predicate"
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AssociatedEventQuery is the builder for querying AssociatedEvent entities.
type AssociatedEventQuery struct {
	config
	ctx            *QueryContext
	order          []associatedevent.OrderOption
	inters         []Interceptor
	predicates     []predicate.AssociatedEvent
	withEarthquake *EarthquakeQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AssociatedEventQuery builder.
func (aeq *AssociatedEventQuery) Where(ps ...predicate.AssociatedEvent) *AssociatedEventQuery {
	aeq.predicates = append(aeq.predicates, ps...)
	return aeq
}

// Limit the number of records to be returned by this query.
func (aeq *AssociatedEventQuery) Limit(limit int) *AssociatedEventQuery {
	aeq.ctx.Limit = &limit
	return aeq
}

// Offset to start from.
func (aeq *AssociatedEventQuery) Offset(offset int) *AssociatedEventQuery {
	aeq.ctx.Offset = &offset
	return aeq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (aeq *AssociatedEventQuery) Unique(unique bool) *AssociatedEventQuery {
	aeq.ctx.Unique = &unique
	return aeq
}

// Order specifies how the records should be ordered.
func (aeq *AssociatedEventQuery) Order(o ...associatedevent.OrderOption) *AssociatedEventQuery {
	aeq.order = append(aeq.order, o...)
	return aeq
}

// QueryEarthquake chains the current query on the "earthquake" edge.
func (aeq *AssociatedEventQuery) QueryEarthquake() *EarthquakeQuery {
	query := (&EarthquakeClient{config: aeq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := aeq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := aeq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(associatedevent.Table, associatedevent.FieldID, selector),
			sqlgraph.To(earthquake.Table, earthquake.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, associatedevent.EarthquakeTable, associatedevent.EarthquakeColumn),
		)
		fromU = sqlgraph.SetNeighbors(aeq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AssociatedEvent entity from the query.
// Returns a *NotFoundError when no AssociatedEvent was found.
func (aeq *AssociatedEventQuery) First(ctx context.Context) (*AssociatedEvent, error) {
	nodes, err := aeq.Limit(1).All(setContextOp(ctx, aeq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{associatedevent.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (aeq *AssociatedEventQuery) FirstX(ctx context.Context) *AssociatedEvent {
	node, err := aeq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AssociatedEvent ID from the query.
// Returns a *NotFoundError when no AssociatedEvent ID was found.
func (aeq *AssociatedEventQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = aeq.Limit(1).IDs(setContextOp(ctx, aeq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{associatedevent.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (aeq *AssociatedEventQuery) FirstIDX(ctx context.Context) int {
	id, err := aeq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AssociatedEvent entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AssociatedEvent entity is found.
// Returns a *NotFoundError when no AssociatedEvent entities are found.
func (aeq *AssociatedEventQuery) Only(ctx context.Context) (*AssociatedEvent, error) {
	nodes, err := aeq.Limit(2).All(setContextOp(ctx, aeq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{associatedevent.Label}
	default:
		return nil, &NotSingularError{associatedevent.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (aeq *AssociatedEventQuery) OnlyX(ctx context.Context) *AssociatedEvent {
	node, err := aeq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AssociatedEvent ID in the query.
// Returns a *NotSingularError when more than one AssociatedEvent ID is found.
// Returns a *NotFoundError when no entities are found.
func (aeq *AssociatedEventQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = aeq.Limit(2).IDs(setContextOp(ctx, aeq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{associatedevent.Label}
	default:
		err = &NotSingularError{associatedevent.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (aeq *AssociatedEventQuery) OnlyIDX(ctx context.Context) int {
	id, err := aeq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AssociatedEvents.
func (aeq *AssociatedEventQuery) All(ctx context.Context) ([]*AssociatedEvent, error) {
	ctx = setContextOp(ctx, aeq.ctx, "All")
	if err := aeq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AssociatedEvent, *AssociatedEventQuery]()
	return withInterceptors[[]*AssociatedEvent](ctx, aeq, qr, aeq.inters)
}

// AllX is like All, but panics if an error occurs.
func (aeq *AssociatedEventQuery) AllX(ctx context.Context) []*AssociatedEvent {
	nodes, err := aeq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AssociatedEvent IDs.
func (aeq *AssociatedEventQuery) IDs(ctx context.Context) (ids []int, err error) {
	if aeq.ctx.Unique == nil && aeq.path != nil {
		aeq.Unique(true)
	}
	ctx = setContextOp(ctx, aeq.ctx, "IDs")
	if err = aeq.Select(associatedevent.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (aeq *AssociatedEventQuery) IDsX(ctx context.Context) []int {
	ids, err := aeq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (aeq *AssociatedEventQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, aeq.ctx, "Count")
	if err := aeq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, aeq, querierCount[*AssociatedEventQuery](), aeq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (aeq *AssociatedEventQuery) CountX(ctx context.Context) int {
	count, err := aeq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (aeq *AssociatedEventQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, aeq.ctx, "Exist")
	switch _, err := aeq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (aeq *AssociatedEventQuery) ExistX(ctx context.Context) bool {
	exist, err := aeq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AssociatedEventQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (aeq *AssociatedEventQuery) Clone() *AssociatedEventQuery {
	if aeq == nil {
		return nil
	}
	return &AssociatedEventQuery{
		config:         aeq.config,
		ctx:            aeq.ctx.Clone(),
		order:          append([]associatedevent.OrderOption{}, aeq.order...),
		inters:         append([]Interceptor{}, aeq.inters...),
		predicates:     append([]predicate.AssociatedEvent{}, aeq.predicates...),
		withEarthquake: aeq.withEarthquake.Clone(),
		// clone intermediate query.
		sql:  aeq.sql.Clone(),
		path: aeq.path,
	}
}

// WithEarthquake tells the query-builder to eager-load the nodes that are connected to
// the "earthquake" edge. The optional arguments are used to configure the query builder of the edge.
func (aeq *AssociatedEventQuery) WithEarthquake(opts ...func(*EarthquakeQuery)) *AssociatedEventQuery {
	query := (&EarthquakeClient{config: aeq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	aeq.withEarthquake = query
	return aeq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		EarthquakeID int `json:"earthquake_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AssociatedEvent.Query().
//		GroupBy(associatedevent.FieldEarthquakeID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (aeq *AssociatedEventQuery) GroupBy(field string, fields ...string) *AssociatedEventGroupBy {
	aeq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AssociatedEventGroupBy{build: aeq}
	grbuild.flds = &aeq.ctx.Fields
	grbuild.label = associatedevent.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		EarthquakeID int `json:"earthquake_id,omitempty"`
//	}
//
//	client.AssociatedEvent.Query().
//		Select(associatedevent.FieldEarthquakeID).
//		Scan(ctx, &v)
func (aeq *AssociatedEventQuery) Select(fields ...string) *AssociatedEventSelect {
	aeq.ctx.Fields = append(aeq.ctx.Fields, fields...)
	sbuild := &AssociatedEventSelect{AssociatedEventQuery: aeq}
	sbuild.label = associatedevent.Label
	sbuild.flds, sbuild.scan = &aeq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AssociatedEventSelect configured with the given aggregations.
func (aeq *AssociatedEventQuery) Aggregate(fns ...AggregateFunc) *AssociatedEventSelect {
	return aeq.Select().Aggregate(fns...)
}

func (aeq *AssociatedEventQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range aeq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, aeq); err != nil {
				return err
			}
		}
	}
	for _, f := range aeq.ctx.Fields {
		if !associatedevent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if aeq.path != nil {
		prev, err := aeq.path(ctx)
		if err != nil {
			return err
		}
		aeq.sql = prev
	}
	return nil
}

func (aeq *AssociatedEventQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AssociatedEvent, error) {
	var (
		nodes       = []*AssociatedEvent{}
		_spec       = aeq.querySpec()
		loadedTypes = [1]bool{
			aeq.withEarthquake != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AssociatedEvent).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AssociatedEvent{config: aeq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, aeq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := aeq.withEarthquake; query != nil {
		if err := aeq.loadEarthquake(ctx, query, nodes, nil,
			func(n *AssociatedEvent, e *Earthquake) { n.Edges.Earthquake = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (aeq *AssociatedEventQuery) loadEarthquake(ctx context.Context, query *EarthquakeQuery, nodes []*AssociatedEvent, init func(*AssociatedEvent), assign func(*AssociatedEvent, *Earthquake)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*AssociatedEvent)
	for i := range nodes {
		fk := nodes[i].EarthquakeID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(earthquake.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "earthquake_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (aeq *AssociatedEventQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := aeq.querySpec()
	_spec.Node.Columns = aeq.ctx.Fields
	if len(aeq.ctx.Fields) > 0 {
		_spec.Unique = aeq.ctx.Unique != nil && *aeq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, aeq.driver, _spec)
}

func (aeq *AssociatedEventQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(associatedevent.Table, associatedevent.Columns, sqlgraph.NewFieldSpec(associatedevent.FieldID, field.TypeInt))
	_spec.From = aeq.sql
	if unique := aeq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if aeq.path != nil {
		_spec.Unique = true
	}
	if fields := aeq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, associatedevent.FieldID)
		for i := range fields {
			if fields[i] != associatedevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if aeq.withEarthquake != nil {
			_spec.Node.AddColumnOnce(associatedevent.FieldEarthquakeID)
		}
	}
	if ps := aeq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := aeq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := aeq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := aeq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (aeq *AssociatedEventQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(aeq.driver.Dialect())
	t1 := builder.Table(associatedevent.Table)
	columns := aeq.ctx.Fields
	if len(columns) == 0 {
		columns = associatedevent.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if aeq.sql != nil {
		selector = aeq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if aeq.ctx.Unique != nil && *aeq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range aeq.predicates {
		p(selector)
	}
	for _, p := range aeq.order {
		p(selector)
	}
	if offset := aeq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := aeq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AssociatedEventGroupBy is the group-by builder for AssociatedEvent entities.
type AssociatedEventGroupBy struct {
	selector
	build *AssociatedEventQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (aegb *AssociatedEventGroupBy) Aggregate(fns ...AggregateFunc) *AssociatedEventGroupBy {
	aegb.fns = append(aegb.fns, fns...)
	return aegb
}

// Scan applies the selector query and scans the result into the given value.
func (aegb *AssociatedEventGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, aegb.build.ctx, "GroupBy")
	if err := aegb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AssociatedEventQuery, *AssociatedEventGroupBy](ctx, aegb.build, aegb, aegb.build.inters, v)
}

func (aegb *AssociatedEventGroupBy) sqlScan(ctx context.Context, root *AssociatedEventQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(aegb.fns))
	for _, fn := range aegb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*aegb.flds)+len(aegb.fns))
		for _, f := range *aegb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*aegb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := aegb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AssociatedEventSelect is the builder for selecting fields of AssociatedEvent entities.
type AssociatedEventSelect struct {
	*AssociatedEventQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (aes *AssociatedEventSelect) Aggregate(fns ...AggregateFunc) *AssociatedEventSelect {
	aes.fns = append(aes.fns, fns...)
	return aes
}

// Scan applies the selector query and scans the result into the given value.
func (aes *AssociatedEventSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, aes.ctx, "Select")
	if err := aes.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AssociatedEventQuery, *AssociatedEventSelect](ctx, aes.AssociatedEventQuery, aes, aes.inters, v)
}

func (aes *AssociatedEventSelect) sqlScan(ctx context.Context, root *AssociatedEventQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(aes.fns))
	for _, fn := range aes.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*aes.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := aes.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
