// Code generated by ent, DO NOT EDIT.

package ent

import (
	"assignment3/ent/associatedevent"
	"assignment3/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AssociatedEventDelete is the builder for deleting a AssociatedEvent entity.
type AssociatedEventDelete struct {
	config
	hooks    []Hook
	mutation *AssociatedEventMutation
}

// Where appends a list predicates to the AssociatedEventDelete builder.
func (aed *AssociatedEventDelete) Where(ps ...predicate.AssociatedEvent) *AssociatedEventDelete {
	aed.mutation.Where(ps...)
	return aed
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (aed *AssociatedEventDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, aed.sqlExec, aed.mutation, aed.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (aed *AssociatedEventDelete) ExecX(ctx context.Context) int {
	n, err := aed.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (aed *AssociatedEventDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(associatedevent.Table, sqlgraph.NewFieldSpec(associatedevent.FieldID, field.TypeInt))
	if ps := aed.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, aed.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	aed.mutation.done = true
	return affected, err
}

// AssociatedEventDeleteOne is the builder for deleting a single AssociatedEvent entity.
type AssociatedEventDeleteOne struct {
	aed *AssociatedEventDelete
}

// Where appends a list predicates to the AssociatedEventDelete builder.
func (aedo *AssociatedEventDeleteOne) Where(ps ...predicate.AssociatedEvent) *AssociatedEventDeleteOne {
	aedo.aed.mutation.Where(ps...)
	return aedo
}

// Exec executes the deletion query.
func (aedo *AssociatedEventDeleteOne) Exec(ctx context.Context) error {
	n, err := aedo.aed.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{associatedevent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (aedo *AssociatedEventDeleteOne) ExecX(ctx context.Context) {
	if err := aedo.Exec(ctx); err != nil {
		panic(err)
	}
}
