// Code generated by ent, DO NOT EDIT.

package ent

import (
	"assignment3/ent/earthquake"
	"assignment3/ent/magnitude"
	"context"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MagnitudeCreate is the builder for creating a Magnitude entity.
type MagnitudeCreate struct {
	config
	mutation *MagnitudeMutation
	hooks    []Hook
}

// SetMagnitudeValue sets the "magnitude_value" field.
func (mc *MagnitudeCreate) SetMagnitudeValue(f float64) *MagnitudeCreate {
	mc.mutation.SetMagnitudeValue(f)
	return mc
}

// SetNillableMagnitudeValue sets the "magnitude_value" field if the given value is not nil.
func (mc *MagnitudeCreate) SetNillableMagnitudeValue(f *float64) *MagnitudeCreate {
	if f != nil {
		mc.SetMagnitudeValue(*f)
	}
	return mc
}

// SetMagnitudeType sets the "magnitude_type" field.
func (mc *MagnitudeCreate) SetMagnitudeType(s string) *MagnitudeCreate {
	mc.mutation.SetMagnitudeType(s)
	return mc
}

// SetNillableMagnitudeType sets the "magnitude_type" field if the given value is not nil.
func (mc *MagnitudeCreate) SetNillableMagnitudeType(s *string) *MagnitudeCreate {
	if s != nil {
		mc.SetMagnitudeType(*s)
	}
	return mc
}

// SetCreatedAt sets the "created_at" field.
func (mc *MagnitudeCreate) SetCreatedAt(t time.Time) *MagnitudeCreate {
	mc.mutation.SetCreatedAt(t)
	return mc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (mc *MagnitudeCreate) SetNillableCreatedAt(t *time.Time) *MagnitudeCreate {
	if t != nil {
		mc.SetCreatedAt(*t)
	}
	return mc
}

// SetUpdatedAt sets the "updated_at" field.
func (mc *MagnitudeCreate) SetUpdatedAt(t time.Time) *MagnitudeCreate {
	mc.mutation.SetUpdatedAt(t)
	return mc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (mc *MagnitudeCreate) SetNillableUpdatedAt(t *time.Time) *MagnitudeCreate {
	if t != nil {
		mc.SetUpdatedAt(*t)
	}
	return mc
}

// SetID sets the "id" field.
func (mc *MagnitudeCreate) SetID(i int) *MagnitudeCreate {
	mc.mutation.SetID(i)
	return mc
}

// AddEarthquakeIDs adds the "earthquakes" edge to the Earthquake entity by IDs.
func (mc *MagnitudeCreate) AddEarthquakeIDs(ids ...int) *MagnitudeCreate {
	mc.mutation.AddEarthquakeIDs(ids...)
	return mc
}

// AddEarthquakes adds the "earthquakes" edges to the Earthquake entity.
func (mc *MagnitudeCreate) AddEarthquakes(e ...*Earthquake) *MagnitudeCreate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return mc.AddEarthquakeIDs(ids...)
}

// Mutation returns the MagnitudeMutation object of the builder.
func (mc *MagnitudeCreate) Mutation() *MagnitudeMutation {
	return mc.mutation
}

// Save creates the Magnitude in the database.
func (mc *MagnitudeCreate) Save(ctx context.Context) (*Magnitude, error) {
	return withHooks(ctx, mc.sqlSave, mc.mutation, mc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mc *MagnitudeCreate) SaveX(ctx context.Context) *Magnitude {
	v, err := mc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mc *MagnitudeCreate) Exec(ctx context.Context) error {
	_, err := mc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mc *MagnitudeCreate) ExecX(ctx context.Context) {
	if err := mc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mc *MagnitudeCreate) check() error {
	return nil
}

func (mc *MagnitudeCreate) sqlSave(ctx context.Context) (*Magnitude, error) {
	if err := mc.check(); err != nil {
		return nil, err
	}
	_node, _spec := mc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	mc.mutation.id = &_node.ID
	mc.mutation.done = true
	return _node, nil
}

func (mc *MagnitudeCreate) createSpec() (*Magnitude, *sqlgraph.CreateSpec) {
	var (
		_node = &Magnitude{config: mc.config}
		_spec = sqlgraph.NewCreateSpec(magnitude.Table, sqlgraph.NewFieldSpec(magnitude.FieldID, field.TypeInt))
	)
	if id, ok := mc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := mc.mutation.MagnitudeValue(); ok {
		_spec.SetField(magnitude.FieldMagnitudeValue, field.TypeFloat64, value)
		_node.MagnitudeValue = value
	}
	if value, ok := mc.mutation.MagnitudeType(); ok {
		_spec.SetField(magnitude.FieldMagnitudeType, field.TypeString, value)
		_node.MagnitudeType = value
	}
	if value, ok := mc.mutation.CreatedAt(); ok {
		_spec.SetField(magnitude.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := mc.mutation.UpdatedAt(); ok {
		_spec.SetField(magnitude.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := mc.mutation.EarthquakesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   magnitude.EarthquakesTable,
			Columns: []string{magnitude.EarthquakesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(earthquake.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MagnitudeCreateBulk is the builder for creating many Magnitude entities in bulk.
type MagnitudeCreateBulk struct {
	config
	err      error
	builders []*MagnitudeCreate
}

// Save creates the Magnitude entities in the database.
func (mcb *MagnitudeCreateBulk) Save(ctx context.Context) ([]*Magnitude, error) {
	if mcb.err != nil {
		return nil, mcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(mcb.builders))
	nodes := make([]*Magnitude, len(mcb.builders))
	mutators := make([]Mutator, len(mcb.builders))
	for i := range mcb.builders {
		func(i int, root context.Context) {
			builder := mcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MagnitudeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mcb *MagnitudeCreateBulk) SaveX(ctx context.Context) []*Magnitude {
	v, err := mcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mcb *MagnitudeCreateBulk) Exec(ctx context.Context) error {
	_, err := mcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mcb *MagnitudeCreateBulk) ExecX(ctx context.Context) {
	if err := mcb.Exec(ctx); err != nil {
		panic(err)
	}
}
