// Code generated by ent, DO NOT EDIT.

package ent

import (
	"assignment3/ent/magnitude"
	"assignment3/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MagnitudeDelete is the builder for deleting a Magnitude entity.
type MagnitudeDelete struct {
	config
	hooks    []Hook
	mutation *MagnitudeMutation
}

// Where appends a list predicates to the MagnitudeDelete builder.
func (md *MagnitudeDelete) Where(ps ...predicate.Magnitude) *MagnitudeDelete {
	md.mutation.Where(ps...)
	return md
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (md *MagnitudeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, md.sqlExec, md.mutation, md.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (md *MagnitudeDelete) ExecX(ctx context.Context) int {
	n, err := md.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (md *MagnitudeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(magnitude.Table, sqlgraph.NewFieldSpec(magnitude.FieldID, field.TypeInt))
	if ps := md.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, md.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	md.mutation.done = true
	return affected, err
}

// MagnitudeDeleteOne is the builder for deleting a single Magnitude entity.
type MagnitudeDeleteOne struct {
	md *MagnitudeDelete
}

// Where appends a list predicates to the MagnitudeDelete builder.
func (mdo *MagnitudeDeleteOne) Where(ps ...predicate.Magnitude) *MagnitudeDeleteOne {
	mdo.md.mutation.Where(ps...)
	return mdo
}

// Exec executes the deletion query.
func (mdo *MagnitudeDeleteOne) Exec(ctx context.Context) error {
	n, err := mdo.md.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{magnitude.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mdo *MagnitudeDeleteOne) ExecX(ctx context.Context) {
	if err := mdo.Exec(ctx); err != nil {
		panic(err)
	}
}
