// Code generated by ent, DO NOT EDIT.

package ent

import (
	"assignment3/ent/request"
	"context"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RequestCreate is the builder for creating a Request entity.
type RequestCreate struct {
	config
	mutation *RequestMutation
	hooks    []Hook
}

// SetRequestURL sets the "request_url" field.
func (rc *RequestCreate) SetRequestURL(s string) *RequestCreate {
	rc.mutation.SetRequestURL(s)
	return rc
}

// SetNillableRequestURL sets the "request_url" field if the given value is not nil.
func (rc *RequestCreate) SetNillableRequestURL(s *string) *RequestCreate {
	if s != nil {
		rc.SetRequestURL(*s)
	}
	return rc
}

// SetRequestMethod sets the "request_method" field.
func (rc *RequestCreate) SetRequestMethod(s string) *RequestCreate {
	rc.mutation.SetRequestMethod(s)
	return rc
}

// SetNillableRequestMethod sets the "request_method" field if the given value is not nil.
func (rc *RequestCreate) SetNillableRequestMethod(s *string) *RequestCreate {
	if s != nil {
		rc.SetRequestMethod(*s)
	}
	return rc
}

// SetRequestHeaders sets the "request_headers" field.
func (rc *RequestCreate) SetRequestHeaders(m map[string]interface{}) *RequestCreate {
	rc.mutation.SetRequestHeaders(m)
	return rc
}

// SetRequestBody sets the "request_body" field.
func (rc *RequestCreate) SetRequestBody(m map[string]interface{}) *RequestCreate {
	rc.mutation.SetRequestBody(m)
	return rc
}

// SetResponseStatusCode sets the "response_status_code" field.
func (rc *RequestCreate) SetResponseStatusCode(i int32) *RequestCreate {
	rc.mutation.SetResponseStatusCode(i)
	return rc
}

// SetNillableResponseStatusCode sets the "response_status_code" field if the given value is not nil.
func (rc *RequestCreate) SetNillableResponseStatusCode(i *int32) *RequestCreate {
	if i != nil {
		rc.SetResponseStatusCode(*i)
	}
	return rc
}

// SetResponseBody sets the "response_body" field.
func (rc *RequestCreate) SetResponseBody(m map[string]interface{}) *RequestCreate {
	rc.mutation.SetResponseBody(m)
	return rc
}

// SetRequestTimestamp sets the "request_timestamp" field.
func (rc *RequestCreate) SetRequestTimestamp(t time.Time) *RequestCreate {
	rc.mutation.SetRequestTimestamp(t)
	return rc
}

// SetNillableRequestTimestamp sets the "request_timestamp" field if the given value is not nil.
func (rc *RequestCreate) SetNillableRequestTimestamp(t *time.Time) *RequestCreate {
	if t != nil {
		rc.SetRequestTimestamp(*t)
	}
	return rc
}

// SetCreatedAt sets the "created_at" field.
func (rc *RequestCreate) SetCreatedAt(t time.Time) *RequestCreate {
	rc.mutation.SetCreatedAt(t)
	return rc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (rc *RequestCreate) SetNillableCreatedAt(t *time.Time) *RequestCreate {
	if t != nil {
		rc.SetCreatedAt(*t)
	}
	return rc
}

// SetUpdatedAt sets the "updated_at" field.
func (rc *RequestCreate) SetUpdatedAt(t time.Time) *RequestCreate {
	rc.mutation.SetUpdatedAt(t)
	return rc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (rc *RequestCreate) SetNillableUpdatedAt(t *time.Time) *RequestCreate {
	if t != nil {
		rc.SetUpdatedAt(*t)
	}
	return rc
}

// SetID sets the "id" field.
func (rc *RequestCreate) SetID(i int) *RequestCreate {
	rc.mutation.SetID(i)
	return rc
}

// Mutation returns the RequestMutation object of the builder.
func (rc *RequestCreate) Mutation() *RequestMutation {
	return rc.mutation
}

// Save creates the Request in the database.
func (rc *RequestCreate) Save(ctx context.Context) (*Request, error) {
	return withHooks(ctx, rc.sqlSave, rc.mutation, rc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rc *RequestCreate) SaveX(ctx context.Context) *Request {
	v, err := rc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rc *RequestCreate) Exec(ctx context.Context) error {
	_, err := rc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rc *RequestCreate) ExecX(ctx context.Context) {
	if err := rc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rc *RequestCreate) check() error {
	return nil
}

func (rc *RequestCreate) sqlSave(ctx context.Context) (*Request, error) {
	if err := rc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	rc.mutation.id = &_node.ID
	rc.mutation.done = true
	return _node, nil
}

func (rc *RequestCreate) createSpec() (*Request, *sqlgraph.CreateSpec) {
	var (
		_node = &Request{config: rc.config}
		_spec = sqlgraph.NewCreateSpec(request.Table, sqlgraph.NewFieldSpec(request.FieldID, field.TypeInt))
	)
	if id, ok := rc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := rc.mutation.RequestURL(); ok {
		_spec.SetField(request.FieldRequestURL, field.TypeString, value)
		_node.RequestURL = value
	}
	if value, ok := rc.mutation.RequestMethod(); ok {
		_spec.SetField(request.FieldRequestMethod, field.TypeString, value)
		_node.RequestMethod = value
	}
	if value, ok := rc.mutation.RequestHeaders(); ok {
		_spec.SetField(request.FieldRequestHeaders, field.TypeJSON, value)
		_node.RequestHeaders = value
	}
	if value, ok := rc.mutation.RequestBody(); ok {
		_spec.SetField(request.FieldRequestBody, field.TypeJSON, value)
		_node.RequestBody = value
	}
	if value, ok := rc.mutation.ResponseStatusCode(); ok {
		_spec.SetField(request.FieldResponseStatusCode, field.TypeInt32, value)
		_node.ResponseStatusCode = value
	}
	if value, ok := rc.mutation.ResponseBody(); ok {
		_spec.SetField(request.FieldResponseBody, field.TypeJSON, value)
		_node.ResponseBody = value
	}
	if value, ok := rc.mutation.RequestTimestamp(); ok {
		_spec.SetField(request.FieldRequestTimestamp, field.TypeTime, value)
		_node.RequestTimestamp = value
	}
	if value, ok := rc.mutation.CreatedAt(); ok {
		_spec.SetField(request.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := rc.mutation.UpdatedAt(); ok {
		_spec.SetField(request.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// RequestCreateBulk is the builder for creating many Request entities in bulk.
type RequestCreateBulk struct {
	config
	err      error
	builders []*RequestCreate
}

// Save creates the Request entities in the database.
func (rcb *RequestCreateBulk) Save(ctx context.Context) ([]*Request, error) {
	if rcb.err != nil {
		return nil, rcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(rcb.builders))
	nodes := make([]*Request, len(rcb.builders))
	mutators := make([]Mutator, len(rcb.builders))
	for i := range rcb.builders {
		func(i int, root context.Context) {
			builder := rcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RequestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rcb *RequestCreateBulk) SaveX(ctx context.Context) []*Request {
	v, err := rcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rcb *RequestCreateBulk) Exec(ctx context.Context) error {
	_, err := rcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rcb *RequestCreateBulk) ExecX(ctx context.Context) {
	if err := rcb.Exec(ctx); err != nil {
		panic(err)
	}
}
