// Code generated by ent, DO NOT EDIT.

package ent

import (
	enttime "assignment3/ent/time"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Time is the model entity for the Time schema.
type Time struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// DateTime holds the value of the "date_time" field.
	DateTime time.Time `json:"date_time,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TimeQuery when eager-loading is set.
	Edges        TimeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TimeEdges holds the relations/edges for other nodes in the graph.
type TimeEdges struct {
	// Earthquakes holds the value of the earthquakes edge.
	Earthquakes []*Earthquake `json:"earthquakes,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// EarthquakesOrErr returns the Earthquakes value or an error if the edge
// was not loaded in eager-loading.
func (e TimeEdges) EarthquakesOrErr() ([]*Earthquake, error) {
	if e.loadedTypes[0] {
		return e.Earthquakes, nil
	}
	return nil, &NotLoadedError{edge: "earthquakes"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Time) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case enttime.FieldID:
			values[i] = new(sql.NullInt64)
		case enttime.FieldDateTime, enttime.FieldCreatedAt, enttime.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Time fields.
func (t *Time) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case enttime.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			t.ID = int(value.Int64)
		case enttime.FieldDateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_time", values[i])
			} else if value.Valid {
				t.DateTime = value.Time
			}
		case enttime.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				t.CreatedAt = value.Time
			}
		case enttime.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				t.UpdatedAt = value.Time
			}
		default:
			t.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Time.
// This includes values selected through modifiers, order, etc.
func (t *Time) Value(name string) (ent.Value, error) {
	return t.selectValues.Get(name)
}

// QueryEarthquakes queries the "earthquakes" edge of the Time entity.
func (t *Time) QueryEarthquakes() *EarthquakeQuery {
	return NewTimeClient(t.config).QueryEarthquakes(t)
}

// Update returns a builder for updating this Time.
// Note that you need to call Time.Unwrap() before calling this method if this Time
// was returned from a transaction, and the transaction was committed or rolled back.
func (t *Time) Update() *TimeUpdateOne {
	return NewTimeClient(t.config).UpdateOne(t)
}

// Unwrap unwraps the Time entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (t *Time) Unwrap() *Time {
	_tx, ok := t.config.driver.(*txDriver)
	if !ok {
		panic("ent: Time is not a transactional entity")
	}
	t.config.driver = _tx.drv
	return t
}

// String implements the fmt.Stringer.
func (t *Time) String() string {
	var builder strings.Builder
	builder.WriteString("Time(")
	builder.WriteString(fmt.Sprintf("id=%v, ", t.ID))
	builder.WriteString("date_time=")
	builder.WriteString(t.DateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(t.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(t.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Times is a parsable slice of Time.
type Times []*Time
