// Code generated by ent, DO NOT EDIT.

package ent

import (
	"assignment3/ent/earthquake"
	"assignment3/ent/predicate"
	"assignment3/ent/type_eathquake"
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TypeEathquakeQuery is the builder for querying Type_eathquake entities.
type TypeEathquakeQuery struct {
	config
	ctx            *QueryContext
	order          []type_eathquake.OrderOption
	inters         []Interceptor
	predicates     []predicate.Type_eathquake
	withEarthquake *EarthquakeQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TypeEathquakeQuery builder.
func (teq *TypeEathquakeQuery) Where(ps ...predicate.Type_eathquake) *TypeEathquakeQuery {
	teq.predicates = append(teq.predicates, ps...)
	return teq
}

// Limit the number of records to be returned by this query.
func (teq *TypeEathquakeQuery) Limit(limit int) *TypeEathquakeQuery {
	teq.ctx.Limit = &limit
	return teq
}

// Offset to start from.
func (teq *TypeEathquakeQuery) Offset(offset int) *TypeEathquakeQuery {
	teq.ctx.Offset = &offset
	return teq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (teq *TypeEathquakeQuery) Unique(unique bool) *TypeEathquakeQuery {
	teq.ctx.Unique = &unique
	return teq
}

// Order specifies how the records should be ordered.
func (teq *TypeEathquakeQuery) Order(o ...type_eathquake.OrderOption) *TypeEathquakeQuery {
	teq.order = append(teq.order, o...)
	return teq
}

// QueryEarthquake chains the current query on the "earthquake" edge.
func (teq *TypeEathquakeQuery) QueryEarthquake() *EarthquakeQuery {
	query := (&EarthquakeClient{config: teq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := teq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := teq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(type_eathquake.Table, type_eathquake.FieldID, selector),
			sqlgraph.To(earthquake.Table, earthquake.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, type_eathquake.EarthquakeTable, type_eathquake.EarthquakeColumn),
		)
		fromU = sqlgraph.SetNeighbors(teq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Type_eathquake entity from the query.
// Returns a *NotFoundError when no Type_eathquake was found.
func (teq *TypeEathquakeQuery) First(ctx context.Context) (*Type_eathquake, error) {
	nodes, err := teq.Limit(1).All(setContextOp(ctx, teq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{type_eathquake.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (teq *TypeEathquakeQuery) FirstX(ctx context.Context) *Type_eathquake {
	node, err := teq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Type_eathquake ID from the query.
// Returns a *NotFoundError when no Type_eathquake ID was found.
func (teq *TypeEathquakeQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = teq.Limit(1).IDs(setContextOp(ctx, teq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{type_eathquake.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (teq *TypeEathquakeQuery) FirstIDX(ctx context.Context) int {
	id, err := teq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Type_eathquake entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Type_eathquake entity is found.
// Returns a *NotFoundError when no Type_eathquake entities are found.
func (teq *TypeEathquakeQuery) Only(ctx context.Context) (*Type_eathquake, error) {
	nodes, err := teq.Limit(2).All(setContextOp(ctx, teq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{type_eathquake.Label}
	default:
		return nil, &NotSingularError{type_eathquake.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (teq *TypeEathquakeQuery) OnlyX(ctx context.Context) *Type_eathquake {
	node, err := teq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Type_eathquake ID in the query.
// Returns a *NotSingularError when more than one Type_eathquake ID is found.
// Returns a *NotFoundError when no entities are found.
func (teq *TypeEathquakeQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = teq.Limit(2).IDs(setContextOp(ctx, teq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{type_eathquake.Label}
	default:
		err = &NotSingularError{type_eathquake.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (teq *TypeEathquakeQuery) OnlyIDX(ctx context.Context) int {
	id, err := teq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Type_eathquakes.
func (teq *TypeEathquakeQuery) All(ctx context.Context) ([]*Type_eathquake, error) {
	ctx = setContextOp(ctx, teq.ctx, "All")
	if err := teq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Type_eathquake, *TypeEathquakeQuery]()
	return withInterceptors[[]*Type_eathquake](ctx, teq, qr, teq.inters)
}

// AllX is like All, but panics if an error occurs.
func (teq *TypeEathquakeQuery) AllX(ctx context.Context) []*Type_eathquake {
	nodes, err := teq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Type_eathquake IDs.
func (teq *TypeEathquakeQuery) IDs(ctx context.Context) (ids []int, err error) {
	if teq.ctx.Unique == nil && teq.path != nil {
		teq.Unique(true)
	}
	ctx = setContextOp(ctx, teq.ctx, "IDs")
	if err = teq.Select(type_eathquake.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (teq *TypeEathquakeQuery) IDsX(ctx context.Context) []int {
	ids, err := teq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (teq *TypeEathquakeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, teq.ctx, "Count")
	if err := teq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, teq, querierCount[*TypeEathquakeQuery](), teq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (teq *TypeEathquakeQuery) CountX(ctx context.Context) int {
	count, err := teq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (teq *TypeEathquakeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, teq.ctx, "Exist")
	switch _, err := teq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (teq *TypeEathquakeQuery) ExistX(ctx context.Context) bool {
	exist, err := teq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TypeEathquakeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (teq *TypeEathquakeQuery) Clone() *TypeEathquakeQuery {
	if teq == nil {
		return nil
	}
	return &TypeEathquakeQuery{
		config:         teq.config,
		ctx:            teq.ctx.Clone(),
		order:          append([]type_eathquake.OrderOption{}, teq.order...),
		inters:         append([]Interceptor{}, teq.inters...),
		predicates:     append([]predicate.Type_eathquake{}, teq.predicates...),
		withEarthquake: teq.withEarthquake.Clone(),
		// clone intermediate query.
		sql:  teq.sql.Clone(),
		path: teq.path,
	}
}

// WithEarthquake tells the query-builder to eager-load the nodes that are connected to
// the "earthquake" edge. The optional arguments are used to configure the query builder of the edge.
func (teq *TypeEathquakeQuery) WithEarthquake(opts ...func(*EarthquakeQuery)) *TypeEathquakeQuery {
	query := (&EarthquakeClient{config: teq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	teq.withEarthquake = query
	return teq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		EarthquakeID int `json:"earthquake_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TypeEathquake.Query().
//		GroupBy(type_eathquake.FieldEarthquakeID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (teq *TypeEathquakeQuery) GroupBy(field string, fields ...string) *TypeEathquakeGroupBy {
	teq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TypeEathquakeGroupBy{build: teq}
	grbuild.flds = &teq.ctx.Fields
	grbuild.label = type_eathquake.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		EarthquakeID int `json:"earthquake_id,omitempty"`
//	}
//
//	client.TypeEathquake.Query().
//		Select(type_eathquake.FieldEarthquakeID).
//		Scan(ctx, &v)
func (teq *TypeEathquakeQuery) Select(fields ...string) *TypeEathquakeSelect {
	teq.ctx.Fields = append(teq.ctx.Fields, fields...)
	sbuild := &TypeEathquakeSelect{TypeEathquakeQuery: teq}
	sbuild.label = type_eathquake.Label
	sbuild.flds, sbuild.scan = &teq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TypeEathquakeSelect configured with the given aggregations.
func (teq *TypeEathquakeQuery) Aggregate(fns ...AggregateFunc) *TypeEathquakeSelect {
	return teq.Select().Aggregate(fns...)
}

func (teq *TypeEathquakeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range teq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, teq); err != nil {
				return err
			}
		}
	}
	for _, f := range teq.ctx.Fields {
		if !type_eathquake.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if teq.path != nil {
		prev, err := teq.path(ctx)
		if err != nil {
			return err
		}
		teq.sql = prev
	}
	return nil
}

func (teq *TypeEathquakeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Type_eathquake, error) {
	var (
		nodes       = []*Type_eathquake{}
		_spec       = teq.querySpec()
		loadedTypes = [1]bool{
			teq.withEarthquake != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Type_eathquake).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Type_eathquake{config: teq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, teq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := teq.withEarthquake; query != nil {
		if err := teq.loadEarthquake(ctx, query, nodes, nil,
			func(n *Type_eathquake, e *Earthquake) { n.Edges.Earthquake = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (teq *TypeEathquakeQuery) loadEarthquake(ctx context.Context, query *EarthquakeQuery, nodes []*Type_eathquake, init func(*Type_eathquake), assign func(*Type_eathquake, *Earthquake)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Type_eathquake)
	for i := range nodes {
		fk := nodes[i].EarthquakeID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(earthquake.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "earthquake_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (teq *TypeEathquakeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := teq.querySpec()
	_spec.Node.Columns = teq.ctx.Fields
	if len(teq.ctx.Fields) > 0 {
		_spec.Unique = teq.ctx.Unique != nil && *teq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, teq.driver, _spec)
}

func (teq *TypeEathquakeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(type_eathquake.Table, type_eathquake.Columns, sqlgraph.NewFieldSpec(type_eathquake.FieldID, field.TypeInt))
	_spec.From = teq.sql
	if unique := teq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if teq.path != nil {
		_spec.Unique = true
	}
	if fields := teq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, type_eathquake.FieldID)
		for i := range fields {
			if fields[i] != type_eathquake.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if teq.withEarthquake != nil {
			_spec.Node.AddColumnOnce(type_eathquake.FieldEarthquakeID)
		}
	}
	if ps := teq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := teq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := teq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := teq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (teq *TypeEathquakeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(teq.driver.Dialect())
	t1 := builder.Table(type_eathquake.Table)
	columns := teq.ctx.Fields
	if len(columns) == 0 {
		columns = type_eathquake.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if teq.sql != nil {
		selector = teq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if teq.ctx.Unique != nil && *teq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range teq.predicates {
		p(selector)
	}
	for _, p := range teq.order {
		p(selector)
	}
	if offset := teq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := teq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TypeEathquakeGroupBy is the group-by builder for Type_eathquake entities.
type TypeEathquakeGroupBy struct {
	selector
	build *TypeEathquakeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tegb *TypeEathquakeGroupBy) Aggregate(fns ...AggregateFunc) *TypeEathquakeGroupBy {
	tegb.fns = append(tegb.fns, fns...)
	return tegb
}

// Scan applies the selector query and scans the result into the given value.
func (tegb *TypeEathquakeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tegb.build.ctx, "GroupBy")
	if err := tegb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TypeEathquakeQuery, *TypeEathquakeGroupBy](ctx, tegb.build, tegb, tegb.build.inters, v)
}

func (tegb *TypeEathquakeGroupBy) sqlScan(ctx context.Context, root *TypeEathquakeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tegb.fns))
	for _, fn := range tegb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tegb.flds)+len(tegb.fns))
		for _, f := range *tegb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tegb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tegb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TypeEathquakeSelect is the builder for selecting fields of TypeEathquake entities.
type TypeEathquakeSelect struct {
	*TypeEathquakeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tes *TypeEathquakeSelect) Aggregate(fns ...AggregateFunc) *TypeEathquakeSelect {
	tes.fns = append(tes.fns, fns...)
	return tes
}

// Scan applies the selector query and scans the result into the given value.
func (tes *TypeEathquakeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tes.ctx, "Select")
	if err := tes.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TypeEathquakeQuery, *TypeEathquakeSelect](ctx, tes.TypeEathquakeQuery, tes, tes.inters, v)
}

func (tes *TypeEathquakeSelect) sqlScan(ctx context.Context, root *TypeEathquakeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tes.fns))
	for _, fn := range tes.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tes.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tes.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
