// Code generated by ent, DO NOT EDIT.

package ent

import (
	"assignment3/ent/earthquake"
	"assignment3/ent/type_eathquake"
	"context"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TypeEathquakeCreate is the builder for creating a Type_eathquake entity.
type TypeEathquakeCreate struct {
	config
	mutation *TypeEathquakeMutation
	hooks    []Hook
}

// SetEarthquakeID sets the "earthquake_id" field.
func (tec *TypeEathquakeCreate) SetEarthquakeID(i int) *TypeEathquakeCreate {
	tec.mutation.SetEarthquakeID(i)
	return tec
}

// SetNillableEarthquakeID sets the "earthquake_id" field if the given value is not nil.
func (tec *TypeEathquakeCreate) SetNillableEarthquakeID(i *int) *TypeEathquakeCreate {
	if i != nil {
		tec.SetEarthquakeID(*i)
	}
	return tec
}

// SetTypeEathquake sets the "type_eathquake" field.
func (tec *TypeEathquakeCreate) SetTypeEathquake(s string) *TypeEathquakeCreate {
	tec.mutation.SetTypeEathquake(s)
	return tec
}

// SetNillableTypeEathquake sets the "type_eathquake" field if the given value is not nil.
func (tec *TypeEathquakeCreate) SetNillableTypeEathquake(s *string) *TypeEathquakeCreate {
	if s != nil {
		tec.SetTypeEathquake(*s)
	}
	return tec
}

// SetCreatedAt sets the "created_at" field.
func (tec *TypeEathquakeCreate) SetCreatedAt(t time.Time) *TypeEathquakeCreate {
	tec.mutation.SetCreatedAt(t)
	return tec
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tec *TypeEathquakeCreate) SetNillableCreatedAt(t *time.Time) *TypeEathquakeCreate {
	if t != nil {
		tec.SetCreatedAt(*t)
	}
	return tec
}

// SetUpdatedAt sets the "updated_at" field.
func (tec *TypeEathquakeCreate) SetUpdatedAt(t time.Time) *TypeEathquakeCreate {
	tec.mutation.SetUpdatedAt(t)
	return tec
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tec *TypeEathquakeCreate) SetNillableUpdatedAt(t *time.Time) *TypeEathquakeCreate {
	if t != nil {
		tec.SetUpdatedAt(*t)
	}
	return tec
}

// SetID sets the "id" field.
func (tec *TypeEathquakeCreate) SetID(i int) *TypeEathquakeCreate {
	tec.mutation.SetID(i)
	return tec
}

// SetEarthquake sets the "earthquake" edge to the Earthquake entity.
func (tec *TypeEathquakeCreate) SetEarthquake(e *Earthquake) *TypeEathquakeCreate {
	return tec.SetEarthquakeID(e.ID)
}

// Mutation returns the TypeEathquakeMutation object of the builder.
func (tec *TypeEathquakeCreate) Mutation() *TypeEathquakeMutation {
	return tec.mutation
}

// Save creates the Type_eathquake in the database.
func (tec *TypeEathquakeCreate) Save(ctx context.Context) (*Type_eathquake, error) {
	return withHooks(ctx, tec.sqlSave, tec.mutation, tec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tec *TypeEathquakeCreate) SaveX(ctx context.Context) *Type_eathquake {
	v, err := tec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tec *TypeEathquakeCreate) Exec(ctx context.Context) error {
	_, err := tec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tec *TypeEathquakeCreate) ExecX(ctx context.Context) {
	if err := tec.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tec *TypeEathquakeCreate) check() error {
	return nil
}

func (tec *TypeEathquakeCreate) sqlSave(ctx context.Context) (*Type_eathquake, error) {
	if err := tec.check(); err != nil {
		return nil, err
	}
	_node, _spec := tec.createSpec()
	if err := sqlgraph.CreateNode(ctx, tec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	tec.mutation.id = &_node.ID
	tec.mutation.done = true
	return _node, nil
}

func (tec *TypeEathquakeCreate) createSpec() (*Type_eathquake, *sqlgraph.CreateSpec) {
	var (
		_node = &Type_eathquake{config: tec.config}
		_spec = sqlgraph.NewCreateSpec(type_eathquake.Table, sqlgraph.NewFieldSpec(type_eathquake.FieldID, field.TypeInt))
	)
	if id, ok := tec.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := tec.mutation.TypeEathquake(); ok {
		_spec.SetField(type_eathquake.FieldTypeEathquake, field.TypeString, value)
		_node.TypeEathquake = value
	}
	if value, ok := tec.mutation.CreatedAt(); ok {
		_spec.SetField(type_eathquake.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := tec.mutation.UpdatedAt(); ok {
		_spec.SetField(type_eathquake.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := tec.mutation.EarthquakeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   type_eathquake.EarthquakeTable,
			Columns: []string{type_eathquake.EarthquakeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(earthquake.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EarthquakeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TypeEathquakeCreateBulk is the builder for creating many Type_eathquake entities in bulk.
type TypeEathquakeCreateBulk struct {
	config
	err      error
	builders []*TypeEathquakeCreate
}

// Save creates the Type_eathquake entities in the database.
func (tecb *TypeEathquakeCreateBulk) Save(ctx context.Context) ([]*Type_eathquake, error) {
	if tecb.err != nil {
		return nil, tecb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tecb.builders))
	nodes := make([]*Type_eathquake, len(tecb.builders))
	mutators := make([]Mutator, len(tecb.builders))
	for i := range tecb.builders {
		func(i int, root context.Context) {
			builder := tecb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TypeEathquakeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tecb *TypeEathquakeCreateBulk) SaveX(ctx context.Context) []*Type_eathquake {
	v, err := tecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tecb *TypeEathquakeCreateBulk) Exec(ctx context.Context) error {
	_, err := tecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tecb *TypeEathquakeCreateBulk) ExecX(ctx context.Context) {
	if err := tecb.Exec(ctx); err != nil {
		panic(err)
	}
}
